[workspace]
members = [
  "memory_reader",
  "stardew_bot",
  "tui_explorer",
  "dll_unpacker",
  "stardew_utils",
  "dotnet_debugger",
  "iterator_extensions",
]
resolver = "2"


[profile.release]
debug = true
