[package]
name = "stardew_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "stardew_bot"
path = "src/main.rs"

[lib]
name = "stardew_bot"

[dependencies]
sysinfo = "*"
itertools = "*"
proc-maps = "*"
process_vm_io = "*"
thiserror = "*"