[workspace]
members = [
  "memory_reader",
  "stardew_bot",
  "stardew_bot/geometry",
  "stardew_bot/game_state",
  "tui_explorer",
  "dll_unpacker",
  "stardew_utils",
  "dotnet_debugger",
  "iterator_extensions",
  "tui_utils",
  "format_utils",
  "bytecode_proc_macros",
]
resolver = "2"


[profile.release]
debug = true
