[package]
name = "dsl_validation"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "*"

dotnet_debugger = { path = "../../dotnet_debugger" }
dsl_ir = { path = "../ir" }
dsl_analysis = { path = "../analysis" }