[package]
name = "dsl_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "*"
arrayvec = "*"
lru = "0.14.0"
itertools = "*"

memory_reader = { path = "../../memory_reader" }
dotnet_debugger = { path = "../../dotnet_debugger" }

dsl_ir = { path = "../ir" }
