[package]
name = "bot_logic"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
thiserror = "*"
derive_more = "*"
priority-queue = "*"

env_var_flag = { path = "../../env_var_flag" }
geometry = { path = "../geometry" }
game_state = { path = "../game_state" }